---
bootstrap_roles:
  - common
  - ssh

default_roles:
  - cli
  - gpg
  - zsh
  - ufw
  - rclone
  - docker
  - system
  - neovim
  - github
  - systemd
  - crontab
  - microcode
  - system-scripts
  - network-manager

compositor_roles:
  - xorg
  - wayland
