---
bootstrap_roles:
  - common
  - ssh

default_roles:
  - cli
  - ufw
  - gpg
  - docker
  - gopass
  - neovim
  - system
  - github
  - systemd
  - crontab
  - xdg-base-dir
  - network-manager

shell_roles:
  - zsh
  - fish

compositor_roles:
  - xorg
  - wayland

dns_primary:
  - 1.1.1.1
  - 1.0.0.1

dns_fallback:
  - 9.9.9.9
  - 149.112.112.112
