#!/usr/bin/env sh

set -x
set -e

ARCHLINUX="arch"
BECOME_FILE_PASSWORD=".secrets/.become_password"
ANSIBLE_VAULT_FILE_PASSWORD=".secrets/.become_password"

validate_secrets() {
	if [ ! -f "$BECOME_FILE_PASSWORD" ]; then
		echo "$BECOME_FILE_PASSWORD is needed"
		exit 1
	fi
	if [ ! -f "$ANSIBLE_VAULT_FILE_PASSWORD" ]; then
		echo "$ANSIBLE_VAULT_FILE_PASSWORD is needed"
		exit 1
	fi
}

detect_os() {
	if [ -f /etc/os-release ]; then
		. /etc/os-release
		echo "$ID"
	else
		uname -s | tr '[:upper:]' '[:lower]'
	fi
}

install_ansible_galaxy() {
	OS=$1
	OS_REQUIREMENTS=""
	if [ -f "requirements/$OS.yml" ]; then
		OS_REQUIREMENTS="requirements/$OS.yml"
	fi
	ansible-galaxy install -r requirements/common.yml "$OS_REQUIREMENTS"
}

setup_archlinux() {
	if ! command -v ansible >/dev/null 2>&1; then
		sudo pacman -S --noconfirm ansible
		sudo pacman -S --noconfirm ansible-core
	fi
}

setup_ubuntu() {
	if ! dpkg -s ansible >/dev/null 2>&1; then
		sudo apt-get install ansible
		sudo apt-get install ansible-core
	fi
}

main() {
	validate_secrets

	system_os=$(detect_os)

	if [ -z "$system_os" ]; then
		echo "System was not recognized"
		exit 1
	fi

	if [ "$system_os" = "$ARCHLINUX" ]; then
		setup_archlinux
	else
		setup_ubuntu
	fi

	install_ansible_galaxy system_os

	ansible-playbook ./local.yml "$@" \
		--become-password-file=.secrets/.become_password

	printf "Finalized succsessfully"
}

main "$@"