- name: Dotfiles config
  hosts: localhost
  connection: local
  vars:
    nix_hm_profile: main
    display_server: "xorg"
    dots_path: "{{ repos_path }}/dotfiles"
    xdg_path: "{{ ansible_user_dir }}/.config"
    repos_path: "{{ ansible_user_dir }}/Documents/github"
    nix_config_path: "/home/{{ host_user }}/.config/nix-config"

  pre_tasks:
    - name: Detect host system
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags: always

  tasks:
    - name: Run bootstrap roles (Always runs first)
      ansible.builtin.include_role:
        name: "{{ item }}"
        apply:
          tags: "{{ item }}"
      loop: "{{ bootstrap_roles }}"
      tags: always

    - name: Compute role execution list
      ansible.builtin.set_fact:
        cli_tags:
          "{{ ansible_run_tags | list | difference(['all', 'always']) }}"
        excluded_display:
          "{{ display_server_roles | difference([display_server]) }}"
      tags: always

    - name: Run target roles
      ansible.builtin.include_role:
        name: "{{ role_item }}"
        apply:
          tags: "{{ role_item }}"
      loop: >-
        {{
          ( (cli_tags if cli_tags | length > 0 else default_roles) +
        [display_server] )
          | difference(excluded_display)
          | difference(bootstrap_roles)
          | unique
          | sort
        }}
      loop_control:
        loop_var: role_item
      tags: always
