- name: Setup Xorg environment
  become: true
  block:
    - name: Install required Xorg packages
      community.general.pacman:
        name:
          - feh
          - rofi
          - maim
          - picom
          - nsxiv
          - xcolor
          - xdotool
          - xorg-xev
          - screenkey
          - unclutter
          - xorg-xinit
          - ueberzugpp
          - xorg-server
          - xorg-xrandr
          - xorg-xsetroot
          - xorg-server-xephyr
        state: present

    - name: Remove Wayland-related packages
      community.general.pacman:
        name: waybar
        state: absent

- name: Setup custom system configurations
  become: true
  vars:
    sys_fonts_dir: /usr/share/fonts/bryant-fonts
    sys_keymaps_dir: /usr/share/kbd/keymaps/bryant-fonts
    sys_x11_conf_dir: /etc/X11/xorg.conf.d
    files_base: files/archlinux
  block:
    - name: Ensure system directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: "0755"
      loop:
        - /etc/udev/rules.d
        - "{{ sys_x11_conf_dir }}"
        - "{{ sys_fonts_dir }}"
        - "{{ sys_keymaps_dir }}"

    - name: Deploy personal fonts
      ansible.builtin.copy:
        src: "{{ files_base }}/usr/share/fonts/bryant-fonts/"
        dest: "{{ sys_fonts_dir }}/"
        owner: root
        group: root
        mode: "0755"
        force: false

    - name: Install vconsole keyboard map
      ansible.builtin.copy:
        src:
          "{{ files_base }}/usr/share/kbd/keymaps/bryant-fonts/bryantd.map.gz"
        dest: "{{ sys_keymaps_dir }}/bryantd.map.gz"
        owner: root
        group: root
        mode: "0644"
        force: false

    - name: Deploy X11 custom keyboard layouts
      ansible.builtin.copy:
        src: "{{ files_base }}/usr/share/X11/xkb/symbols/"
        dest: /usr/share/X11/xkb/symbols/
        owner: root
        group: root
        mode: "0644"
        force: false

    - name: Deploy system environment file
      ansible.builtin.copy:
        src: "{{ files_base }}/etc/environment"
        dest: /etc/environment
        owner: root
        group: root
        mode: "0644"
        force: true

    - name: Refresh font cache
      ansible.builtin.command: fc-cache -f -v
      register: fontcache
      changed_when: false
      failed_when: fontcache.rc != 0

    - name: Deploy X11 keyboard configuration
      ansible.builtin.copy:
        src: "{{ files_base }}/etc/X11/xorg.conf.d/00-keyboard.conf"
        dest: "{{ sys_x11_conf_dir }}/00-keyboard.conf"
        mode: "0644"
        force: true

    - name: Deploy vconsole configuration
      ansible.builtin.copy:
        src: "{{ files_base }}/etc/vconsole.conf"
        dest: /etc/vconsole.conf
        mode: "0644"
        force: true
