- name: Load OS-specific tasks if available
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Clone and build ST terminal emulator
  vars:
    personal_github: "git@personal.github:pazbryant7"
  block:
    - name: Clone ST repository
      ansible.builtin.git:
        repo: "{{ personal_github }}/st.git"
        dest: "{{ github_dir }}/st"
        version: main
        update: false

    - name: Build and install ST
      become: true
      ansible.builtin.command:
        cmd: make clean install
        chdir: "{{ github_dir }}/st"
        creates: /usr/local/bin/st

    - name: Symlink ST to xterm
      become: true
      ansible.builtin.file:
        src: /usr/local/bin/st
        dest: /usr/bin/xterm
        state: link

- name: Clone and build DWM window manager
  vars:
    personal_github: "git@personal.github:pazbryant7"
  block:
    - name: Clone DWM repository
      ansible.builtin.git:
        repo: "{{ personal_github }}/dwm.git"
        dest: "{{ github_dir }}/dwm"
        version: main
        update: false

    - name: Build and install DWM
      become: true
      ansible.builtin.command:
        cmd: make clean install
        chdir: "{{ github_dir }}/dwm"
        creates: /usr/local/bin/dwm

- name: Clone and build slstatus
  vars:
    personal_github: "git@personal.github:pazbryant7"
  block:
    - name: Clone slstatus repository
      ansible.builtin.git:
        repo: "{{ personal_github }}/slstatus.git"
        dest: "{{ github_dir }}/slstatus"
        version: main
        update: false

    - name: Build and install slstatus
      become: true
      ansible.builtin.command:
        cmd: make clean install
        chdir: "{{ github_dir }}/slstatus"
        creates: /usr/local/bin/slstatus
