name: ansible-ubuntu

services:
  ansible:
    build:
      context: ../../
      dockerfile: docker/ubuntu/Dockerfile
      args:
        TEST_USER: testuser
    image: ansible-ubuntu-dev:latest
    container_name: ansible-ubuntu-test
    volumes:
      - ../../:/ansible
      - ../../.secrets:/ansible/.secrets:ro
    tty: true
    stdin_open: true
    environment:
      - ANSIBLE_FORCE_COLOR=1
