- name: Ensure clone github repositories
  become: false
  ansible.builtin.git:
    repo: "git@personal.github:pazbryant7/{{ item }}.git"
    dest: "{{ repos_path }}/{{ item }}"
    version: main
    update: false
    recursive: true
    clone: true
    single_branch: true
    accept_hostkey: true
  loop:
    - pass
    - nvim
    - media
    - notes
    - youtube
    - leetcode
    - portfolio
    - pass-backup
    - boilerplate
