- name: Get distribution
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: Run tasks for {{ host_os }}
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Enable and start essential system services
  become: true
  when: systemd_status.rc == 0
  block:
    - name: Enable and start systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved.service
        enabled: true
        state: started

    - name: Enable and start cronie
      ansible.builtin.systemd:
        name: cronie.service
        enabled: true
        state: started

    - name: Enable and start syncthing for user
      ansible.builtin.systemd:
        name: "syncthing@{{ host_user }}.service"
        enabled: true
        state: started

- name: Enable mpd user service
  ansible.builtin.systemd:
    name: mpd.service
    scope: user
    enabled: true
    state: started
  when: systemd_status.rc == 0

- name: Reload and reexec systemd
  become: true
  when: systemd_status.rc == 0
  block:
    - name: Reload systemd manager configuration
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Reexec systemd
      ansible.builtin.systemd:
        daemon_reexec: true
