- name: "Get distribution"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: "Run tasks for {{ host_os }}"
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Ensure .ssh/private directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/private"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid | default(ansible_user_id) }}"

- name: Deploy SSH config files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item }}"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid | default(ansible_user_id) }}"
  loop:
    - config
    - known_hosts

- name: Import SSH private keys
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.ssh/private/{{ item.name }}"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid | default(ansible_user_id) }}"
    content: "{{ lookup('file', item.src) | regex_replace('\\s*$', '\n') }}"
  loop:
    - { name: "personal_github", src: ".secrets/ssh/github/personal_github" }
    - { name: "work_github", src: ".secrets/ssh/github/work_github" }
