- name: "Get distribution"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: "Run tasks for {{ host_os }}"
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Setup SSH
  vars:
    dir: "{{ ansible_user_dir }}/.ssh"
    secrets: "{{ playbook_dir }}/.secrets/ssh/github"
    private_dir: "{{ ansible_user_dir }}/.ssh/private"
  block:
    - name: Ensure ssh directory exists
      ansible.builtin.file:
        path: "{{ private_dir }}"
        state: directory
        mode: "0700"
        owner: "{{ host_user }}"
        group: "{{ ansible_user_gid | default(host_user) }}"

    - name: Deploy SSH config files
      ansible.builtin.copy:
        src: "files/common/{{ file }}"
        dest: "{{ dir }}/{{ file }}"
        mode: "0600"
        owner: "{{ host_user }}"
        group: "{{ ansible_user_gid | default(host_user) }}"
      loop:
        - config
        - known_hosts
      loop_control:
        loop_var: file

    - name: Import SSH private keys
      ansible.builtin.copy:
        src: "{{ secrets }}/{{ ssh_key.name }}"
        dest: "{{ private_dir }}/{{ ssh_key.name }}"
        mode: "0600"
        owner: "{{ host_user }}"
        group: "{{ ansible_user_gid | default(host_user) }}"
      loop:
        - name: personal_github
        - name: work_github
      loop_control:
        loop_var: ssh_key
