- name: Setup SSH
  vars:
    dir: "{{ ansible_env.HOME }}/.ssh"
    secrets: ".secrets/ssh/github"
    private_dir: "{{ ansible_env.HOME }}/.ssh/private"
  block:
    - name: Ensure ssh directory exists
      ansible.builtin.file:
        path: "{{ private_dir }}"
        state: directory
        mode: "0700"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid | default(ansible_user_id) }}"

    - name: Deploy SSH config files
      ansible.builtin.copy:
        src: "files/common/{{ file }}"
        dest: "{{ dir }}/{{ file }}"
        mode: "0600"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid | default(ansible_user_id) }}"
      loop:
        - config
        - known_hosts
      loop_control:
        loop_var: file

    - name: Import SSH private keys
      ansible.builtin.copy:
        src: "{{ secrets }}/{{ ssh_key.name }}"
        dest: "{{ private_dir }}/{{ ssh_key.name }}"
        mode: "0600"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid | default(ansible_user_id) }}"
      loop:
        - name: personal_github
        - name: work_github
      loop_control:
        loop_var: ssh_key
