- name: Ensure openssh is installed
  become: true
  community.general.xbps:
    name: openssh
    state: present

- name: Enable and start SSH daemon via runit
  become: true
  ansible.builtin.file:
    src: /etc/sv/sshd
    dest: /var/service/sshd
    state: link
