- name: Setup pacman
  become: true
  vars:
    hooks_path: /etc/pacman.d/hooks
    pacman_conf: /etc/pacman.conf
  block:
    - name: Ensure pacman hooks directory exists
      ansible.builtin.file:
        path: "{{ hooks_path }}"
        state: directory
        mode: "0755"

    - name: Install pacman update hook
      ansible.builtin.copy:
        src: files/archlinux/etc/pacman.d/hooks/update-apps.hook
        dest: "{{ hooks_path }}/update-apps.hook"
        mode: "0644"
        force: false

    - name: Enable pacman ParallelDownloads
      ansible.builtin.lineinfile:
        path: "{{ pacman_conf }}"
        regexp: '^#?ParallelDownloads\s*='
        line: "ParallelDownloads = 5"
        backup: true

    - name: Enable pacman Color
      ansible.builtin.lineinfile:
        path: "{{ pacman_conf }}"
        regexp: '^#?\s*Color\s*$'
        line: "Color"
        insertafter: '^\[options\]'
        backup: true

    - name: Enable pacman ILoveCandy
      ansible.builtin.lineinfile:
        path: "{{ pacman_conf }}"
        regexp: '^#?\s*ILoveCandy\s*$'
        line: "ILoveCandy"
        insertafter: '^\[options\]'

    - name: Enable multilib repository
      ansible.builtin.replace:
        path: "{{ pacman_conf }}"
        regexp: '^#\s*\[multilib\]\n#\s*Include = /etc/pacman.d/mirrorlist'
        replace: '[multilib]\nInclude = /etc/pacman.d/mirrorlist'
        backup: true

- name: Finish setup and reload
  become: true
  block:
    - name: Configure timezone and NTP
      when: ansible_service_mgr == 'systemd'
      block:
        - name: Set timezone to America/Merida
          community.general.timezone:
            name: America/Merida

        - name: Enable NTP synchronization via systemd-timesyncd
          ansible.builtin.systemd:
            name: systemd-timesyncd.service
            enabled: true
            state: started

    - name: Flush DNS cache (resolvectl)
      ansible.builtin.command:
        cmd: resolvectl flush-caches
      changed_when: false
      when: ansible_service_mgr == 'systemd'

    - name: Setup consolefont and keymap mkinitcpio.conf
      ansible.builtin.lineinfile:
        path: /etc/mkinitcpio.conf
        regexp: '^HOOKS=\((?!.*keymap)(?!.*consolefont)(.*)\)'
        line: 'HOOKS=(\1 keymap consolefont)'
        backrefs: true
      notify: Regenerate mkinitcpio binary image
