- name: Get distribution
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: Run tasks for {{ host_os }}
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Setup rclone
  become: false
  vars:
    dir: "{{ ansible_env.HOME }}/.config/rclone"
    config_file: ".secrets/xdg_config/rclone/rclone.conf"
  block:
    - name: Ensure rclone config directory exists
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
        mode: "0700"

    - name: Deploy rclone configuration
      ansible.builtin.copy:
        src: "{{ config_file }}"
        dest: "{{ dir }}/rclone.conf"
        mode: "0600"
        force: false


- name: Setup Github CLI
  become: false
  vars:
    dir: "{{ ansible_env.HOME }}/.config/gh"
    config_file: ".secrets/xdg_config/gh/"
  block:
    - name: Ensure Github CLI config directory exists
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
        mode: "0700"

    - name: Deploy Github CLI configuration files
      ansible.builtin.copy:
        src: "{{ config_file }}"
        dest: "{{ dir }}/"
        mode: "0600"
        force: false
