- name: "Get distribution"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: "Run tasks for {{ host_os }}"
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Configure UFW firewall
  become: true
  block:
    - name: Set default policies
      community.general.ufw:
        direction: "{{ item.direction }}"
        default: "{{ item.policy }}"
      loop:
        - { direction: "incoming", policy: "deny" }
        - { direction: "outgoing", policy: "allow" }

    - name: Allow LAN access
      community.general.ufw:
        rule: allow
        from_ip: 192.168.0.0/24

    - name: Allow Port Forwarding
      community.general.ufw:
        rule: allow
        port: "17349"
        proto: "{{ item }}"
      loop:
        - tcp
        - udp
      become: true

    - name: Allow Deluge
      community.general.ufw:
        rule: allow
        app: Deluge

    - name: Limit SSH brute-force
      community.general.ufw:
        rule: limit
        app: SSH

    - name: Enable UFW
      community.general.ufw:
        state: enabled
