- name: Get distribution
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: Run tasks for {{ host_os }}
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Check if iptables is available
  ansible.builtin.command: iptables -L
  register: iptables_status
  changed_when: false
  failed_when: false
  become: true

- name: Configure UFW firewall
  become: true
  when: iptables_status.rc == 0
  block:
    - name: Allow UFW forwarding for Docker
      ansible.builtin.lineinfile:
        path: /etc/default/ufw
        regexp: "^DEFAULT_FORWARD_POLICY="
        line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

    - name: Set default policies
      community.general.ufw:
        direction: "{{ ufw_item.direction }}"
        default: "{{ ufw_item.policy }}"
      loop:
        - { direction: "incoming", policy: "deny" }
        - { direction: "outgoing", policy: "allow" }
      loop_control:
        loop_var: ufw_item

    - name: Allow LAN access
      community.general.ufw:
        rule: allow
        from_ip: 192.168.0.0/24

    - name: Allow Docker networks
      community.general.ufw:
        rule: allow
        from_ip: 172.16.0.0/12

    - name: Allow Deluge
      community.general.ufw:
        rule: allow
        app: Deluge

    - name: Allow qBittorrent
      community.general.ufw:
        rule: allow
        app: qBittorrent

    - name: Limit SSH brute-force
      community.general.ufw:
        rule: limit
        app: SSH

    - name: Enable UFW
      community.general.ufw:
        state: enabled
