- name: Setup UFW firewall (Void Linux)
  become: true
  block:
    - name: Install ufw
      community.general.xbps:
        name: ufw
        state: present

    - name: Enable and start ufw service (runit)
      ansible.builtin.file:
        src: /etc/sv/ufw
        dest: /var/service/ufw
        state: link

    - name: Ensure UFW is enabled and active
      community.general.ufw:
        state: enabled
