- name: Ensure cronie is installed (Arch)
  become: true
  community.general.pacman:
    name: cronie
    state: present

- name: Ensure cronie service is enabled and running (systemd)
  become: true
  ansible.builtin.systemd:
    name: cronie
    state: started
    enabled: yes

- name: Copy script to the target system
  become: true
  ansible.builtin.copy:
    src: "files/common/backup-notes"
    dest: "/usr/local/bin/backup-notes"
    owner: root
    group: root
    mode: "0755"

- name: Create hourly cron task
  ansible.builtin.cron:
    name: "Execute backup-notes once per hour"
    minute: "0"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: "{{ host_user }}"
    job: "/usr/local/bin/backup-notes"
