- name: Setup cron jobs
  vars:
    crontab_path: "{{ ansible_env.HOME }}/bin/crontab"
  block:
    - name: Ensure Backup-notes cron job exists
      ansible.builtin.cron:
        name: "Backup notes"
        minute: "0"
        hour: "*"
        job: "{{ crontab_path }}/backup-notes > /tmp/cron-backup-notes 2>&1"
        state: present
        user: "{{ ansible_user_id }}"
