- name: Ensure Backup-notes cron job exists
  ansible.builtin.cron:
    name: "Backup notes"
    minute: "0"
    hour: "*"
    job: >
      {{ ansible_env.HOME }}/bin/crontab/backup-notes > /tmp/cron-backup-notes
      2>&1
    state: present
    user: "{{ ansible_user_id }}"

- name: Ensure himalaya-cron-refresh cron job exists
  ansible.builtin.cron:
    name: "Himalaya token refresh"
    minute: "*/30"
    hour: "*"
    job: >
      {{ ansible_env.HOME }}/bin/crontab/himalaya-cron-refresh >
      /tmp/cron-himalaya-cron-refresh 2>&1
    state: present
    user: "{{ ansible_user_id }}"
