- name: Setup cron jobs
  vars:
    src_dir: "{{ role_path }}/tasks/files/"
  block:
    - name: Ensure backup notes cron job exists
      ansible.builtin.cron:
        name: "Backup notes"
        minute: "0"
        hour: "*"
        job: "{{ src_dir }}/backup-notes > /tmp/cron-backup-notes 2>&1"
        state: present
        user: "{{ ansible_user_id }}"
