- name: Ensure conflicting system dotfiles are removed before stowing
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: absent
  loop:
    - .zshrc
    - .bashrc
    - .zshenv
    - .xinitrc
    - .zprofile
    - .tmux.conf
    - .gitconfig

- name: Setup dotfiles with stow
  ansible.builtin.command:
    cmd: stow --dir="{{ dotfiles_dir }}" --target="{{ ansible_user_dir }}" --restow .
  args:
    chdir: "{{ dotfiles_dir }}"
  register: stowstdr
  changed_when: stowstdr.rc != 0
