- name: Ensure base development packages are installed (Arch)
  become: true
  community.general.pacman:
    name:
      - base
      - sudo
      - linux
      - man-db
      - linux-lts
      - base-devel
      - efibootmgr
      - linux-headers
      - linux-firmware
      - linux-lts-headers
    state: present
