- name: Ensure base development packages are installed
  become: true
  community.general.pacman:
    name:
      - ufw
      - sudo
      - tmux
      - base
      - dunst
      - linux
      - rtkit
      - xclip
      - cronie
      - man-db
      - ntfs-3g
      - pipewire
      - libnotify
      - linux-lts
      - efibootmgr
      - base-devel
      - pipewire-alsa
      - linux-headers
      - terminus-font
      - pipewire-jack
      - pipewire-pulse
      - networkmanager
      - zram-generator
      - linux-firmware
      - noto-fonts-emoji
      - linux-lts-headers
      - gst-plugin-pipewire
      - zram-generator
    state: present
