- name: Ensure base development packages are installed (Artix)
  become: true
  community.general.pacman:
    name:
      - sudo
      - man-db
      - efibootmgr
      - linux-artix
      - artix-base
      - linux-firmware
      - linux-lts-artix
      - artix-base-devel
      - linux-artix-headers
      - linux-lts-artix-headers
    state: present
