- name:
    Ensure base development packages, repos, and firmware are installed (Void)
  become: true
  community.general.xbps:
    name:
      - base-system
      - void-repo-nonfree
      - void-repo-multilib
      - void-repo-multilib-nonfree
    state: present
    update_cache: true
