- name: Install docker
  become: true
  community.general.pacman:
    name:
      - docker
      - docker-buildx
      - docker-compose
    state: present

- name: Configure Docker (On-Demand via Systemd)
  become: true
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  loop:
    - { name: "docker.service", enabled: false, state: "stopped" }
    - { name: "docker.socket", enabled: true, state: "started" }
