- name: Get distribution
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: Run tasks for {{ host_os }}
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Ensure gpg directory exists
  become: false
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid | default(ansible_user_id) }}"

- name: Check if private key file exists
  become: false
  ansible.builtin.stat:
    path: ".secrets/gpg/private-key.asc"
  register: gpg_key_file

- name: Copy GPG private key to keyring directory
  become: false
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.gnupg/private_key.asc"
    mode: "0600"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid | default(ansible_user_id) }}"
    content: "{{ lookup('file', '.secrets/gpg/private-key.asc') }}"
  when: gpg_key_file.stat.exists

- name: Import private key into GPG keyring
  become: false
  ansible.builtin.command:
    cmd: gpg --batch --import {{ ansible_env.HOME }}/.gnupg/private_key.asc
  register: gpg_import
  changed_when: "'secret key imported' in gpg_import.stderr"
  when: gpg_key_file.stat.exists

- name: Get GPG key fingerprint
  become: false
  ansible.builtin.shell:
    cmd: >
      gpg --with-colons --import-options show-only --import {{ ansible_env.HOME
      }}/.gnupg/private_key.asc | awk -F: '$1 == "fpr" { print $10; exit }'
  register: gpg_fingerprint
  changed_when: false
  when: gpg_key_file.stat.exists

- name: Set ultimate trust on GPG key
  become: false
  ansible.builtin.shell:
    cmd:
      echo "{{ gpg_fingerprint.stdout }}:6:" | gpg --batch --import-ownertrust
  changed_when: false
  when: gpg_key_file.stat.exists
