- name: Get distribution
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: Run tasks for {{ host_os }}
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Manage Main GPG Key
  become: false
  vars:
    dir: "{{ ansible_env.HOME }}/.gnupg"
    key: ".secrets/gpg/private-key.asc"
    key_dest: "{{ dir }}/private_key.asc"
  block:
    - name: Ensure gpg directory exists
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
        mode: "0700"
        owner: "{{ host_user }}"
        group: "{{ host_user }}"

    - name: Check if private key file exists
      ansible.builtin.stat:
        path: "{{ key }}"
      register: key_file

    - name: Import and trust main private key
      when: key_file.stat.exists
      block:
        - name: Copy GPG private key
          ansible.builtin.copy:
            dest: "{{ key_dest }}"
            mode: "0600"
            owner: "{{ host_user }}"
            group: "{{ host_user }}"
            content: "{{ lookup('file', key) }}"

        - name: Import private key into keyring
          ansible.builtin.command: gpg --batch --import {{ key_dest }}
          register: imported_key
          changed_when: "'secret key imported' in imported_key.stderr"

        - name: Get main GPG key fingerprint
          ansible.builtin.shell: |
            gpg --with-colons --show-keys {{ key_dest }} 2>&1 | awk -F: '$1 == "fpr" { print $10; exit }'
          register: gpg_fingerprint
          changed_when: false

        - name: Set ultimate trust on main GPG key
          ansible.builtin.shell: |
            echo "{{ gpg_fingerprint.stdout }}:6:" | gpg --batch --import-ownertrust
          changed_when: false
