- name: Ensure install packages
  become: true
  community.general.pacman:
    name:
      - cronie
      - systemd
    state: present

- name: Enable and start essential system services
  become: true
  when: systemd_status.rc == 0
  block:
    - name: Enable and start systemd-resolved
      ansible.builtin.systemd:
        name: systemd-resolved.service
        enabled: true
        state: started

    - name: Enable and start cronie
      ansible.builtin.systemd:
        name: cronie.service
        enabled: true
        state: started

- name: Reload and reexec systemd
  become: true
  when: systemd_status.rc == 0
  block:
    - name: Reload systemd manager configuration
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Reexec systemd
      ansible.builtin.systemd:
        daemon_reexec: true
