- name: Ensure packages and their runit services are installed
  become: true
  community.general.pacman:
    name:
      - ufw
      - dbus
      - cronie
      - docker
      - chrony
      - socklog
      - elogind
      - ufw-runit
      - dbus-runit
      - chrony-runit
      - cronie-runit
      - docker-runit
      - elogind-runit
      - socklog-runit
      - docker-buildx
      - docker-compose
    state: present

- name: Enable system services via runit
  become: true
  ansible.builtin.file:
    src: "/etc/sv/{{ item }}"
    dest: "/run/runit/service/{{ item }}"
    state: link
  loop:
    - ufw
    - dbus
    - cronie
    - docker
    - elogind
    - chronyd
    - socklog-unix

- name: Add current user to socklog group
  become: true
  ansible.builtin.user:
    name: "{{ host_user }}"
    groups: socklog
    append: true
