- name: Ensure packages and their runit services are installed
  become: true
  community.general.pacman:
    name:
      - ufw
      - ufw-runit

      - dbus
      - dbus-runit

      - cronie
      - cronie-runit

      - docker
      - docker-runit
      - docker-buildx
      - docker-compose

      - chrony
      - chrony-runit

      - elogind
      - elogind-runit

      - socklog
    state: present

- name: Enable system services via runit
  become: true
  ansible.builtin.file:
    src: "/etc/runit/sv/{{ item }}"
    dest: "/run/runit/service/{{ item }}"
    state: link
  loop:
    - ufw
    - dbus
    - cronie
    - docker
    - chrony
    - elogind
    - socklog
