- name: Ensure packages are installed via xbps
  become: true
  community.general.xbps:
    name:
      - ufw
      - dbus
      - cronie
      - chrony
      - cronie
      - docker
      - elogind
      - socklog-void
      - docker-buildx
    state: present

- name: Enable system services via runit
  become: true
  ansible.builtin.file:
    src: "/etc/sv/{{ item }}"
    dest: "/var/service/{{ item }}"
    state: link
  loop:
    - ufw
    - dbus
    - cronie
    - docker
    - elogind
    - chronyd
    - nanoklogd
    - socklog-unix

- name: Add current user to socklog group
  become: true
  ansible.builtin.user:
    name: "{{ host_user }}"
    groups: socklog
    append: true
