- name: Ensure packages are installed via xbps
  become: true
  community.general.xbps:
    name:
      - cronie
      - chrony
      - socklog-void
    state: present

- name: Enable system services via runit
  become: true
  ansible.builtin.file:
    src: "/etc/sv/{{ item }}"
    dest: "/var/service/{{ item }}"
    state: link
  loop:
    - dbus
    - cronie
    - chronyd
    - nanoklogd
    - socklog-unix
