- name: Ensure common cli tools are installed
  become: true
  community.general.pacman:
    name:
      - jq
      - go
      - uv
      - fd
      - lf
      - fzf
      - mpc
      - git
      - bat
      - xsv
      - mpv
      - eza
      - mpd
      - lua
      - stow
      - just
      - less
      - lsof
      - tmux
      - aria2
      - atuin
      - unzip
      - unrar
      - pcman
      - rsync
      - steam
      - qt6ct
      - yt-dlp
      - gopass
      - rustup
      - rclone
      - zoxide
      - ncmpcpp
      - ripgrep
      - zathura
      - lazygit
      - jujutsu
      - poppler
      - calibre
      - nwg-look
      - luarocks
      - trash-cli
      - hyperfine
      - fastfetch
      - gammastep
      - alacritty
      - breeze-gtk
      - lazydocker
      - github-cli
      - python-pip
      - qbittorrent
      - pavucontrol
      - imagemagick
      - oath-toolkit
      - breeze-icons
      - bitwarden-cli
      - android-tools
      - noto-fonts-cjk
      - pacman-contrib
      - translate-shell
      - tree-sitter-cli
      - zathura-pdf-mupdf
      - capitaine-cursors
      - ttf-nerd-fonts-symbols
    state: present
