- name: Ensure common cli tools are installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - go
    - uv
    - fd
    - xh
    - fzf
    - mpc
    - git
    - bat
    - xsv
    - mpv
    - eza
    - mpd
    - lua
    - stow
    - hurl
    - just
    - sqlc
    - tmux
    - fish
    - tree
    - less
    - yazi
    - dust
    - lsof
    - 7zip
    - aria2
    - atuin
    - pgcli
    - rsync
    - qt6ct
    - yt-dlp
    - pastel
    - rustup
    - gopass
    - ccache
    - rclone
    - zoxide
    - ncmpcpp
    - ripgrep
    - firefox
    - zathura
    - pcmanfm
    - jujutsu
    - poppler
    - calibre
    - img2pdf
    - starship
    - websocat
    - libpulse
    - luarocks
    - patchelf
    - fastfetch
    - gammastep
    - alacritty
    - watchexec
    - bandwhich
    - syncthing
    - hyperfine
    - breeze-gtk
    - typescript
    - github-cli
    - pandoc-cli
    - python-pip
    - qbittorrent
    - pavucontrol
    - imagemagick
    - breeze-icons
    - android-tools
    - noto-fonts-cjk
    - pacman-contrib
    - translate-shell
    - tree-sitter-cli
    - zathura-pdf-mupdf
    - capitaine-cursors
    - perl-image-exiftool

- name: Install AUR packages using yay
  kewlfft.aur.aur:
    use: yay
    name: "{{ item }}"
    state: present
  loop:
    - bun-bin
    - lazydocker
    - ventoy-bin
    - numbat-bin
    - grpcurl-bin
    - dragon-drop
    - thorium-browser-bin
