- name: Ensure common cli tools are installed
  become: true
  community.general.pacman:
    name:
      - jq
      - uv
      - fd
      - lf
      - mpc
      - xsv
      - bat
      - feh
      - fzf
      - mpd
      - git
      - lua
      - eza
      - mpv
      - less
      - lsof
      - tmux
      - just
      - stow
      - rofi
      - aria2
      - dunst
      - atuin
      - qt6ct
      - steam
      - nsxiv
      - rsync
      - zoxide
      - bottom
      - yt-dlp
      - rclone
      - gopass
      - jujutsu
      - ripgrep
      - pcmanfm
      - ncmpcpp
      - zathura
      - lazygit
      - calibre
      - ntfs-3g
      - poppler
      - luarocks
      - pipewire
      - nwg-look
      - hyperfine
      - fastfetch
      - trash-cli
      - alacritty
      - gammastep
      - lazydocker
      - github-cli
      - python-pip
      - breeze-gtk
      - imagemagick
      - qbittorrent
      - pavucontrol
      - breeze-icons
      - oath-toolkit
      - terminus-font
      - android-tools
      - noto-fonts-cjk
      - networkmanager
      - zram-generator
      - translate-shell
      - tree-sitter-cli
      - noto-fonts-emoji
      - ttf-nerd-fonts-symbols
    state: present
